apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9deploy
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: web    # Pod 작성시 이 부분이 포함되어야 한다.
  template:       # 여기서부터 Pod 작성
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: aws9ctn
          image: ghzx55/aws9:green
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port
    port: 8080      # cluster-ip 의 포트 번호
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web        # Pod의 Label을 지정해 주어야 함
